# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quest1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.6.0'
    pod 'RxCocoa', '6.6.0'
  # Pods for quest1

end
